[project]
name = "ocr"
version = "0.1.0"
description = "OCR PIPELINE"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.5",
    "opencv-python>=4.11.0.86",
    "pillow>=12.0.0",
    "python-dotenv>=1.2.1",
    "regex==2024.9.11",
    "requests>=2.32.5",
]
